### PR TITLE
Performance tests

### PR DESCRIPTION
**Pull request by palimondo**
Add performance tests for raw and bounded generator and a full range and bounded number sequences.

Resolves Issue #8.

### CODE REVIEW

**Comment by palimondo** [comment]
See also the performance measurement results from the [Travis build](https://travis-ci.org/lemire/SwiftWyhash/builds/543616822?utm_source=github_status&utm_medium=notification) ([raw log](https://api.travis-ci.org/v3/job/543616823/log.txt)).

**Comment by palimondo** [comment]
@lemire please review

**Comment by lemire** [comment]
This is fine with the caveat that these performance tests are run over debug builds.

Merging.

**Review by lemire — APPROVED** [review]

**Comment by lemire** [comment]
See 
https://github.com/lemire/SwiftWyhashBenchmark

**Pull request merged**
